### ISSUE TITLE
Question - What is different about this library from the AOSP implementation of org.json?

### ISSUE THREAD

**Issue by jkasten2** [tdunning/open-json#16]
This repo's README says:
>Thanks to the Android team for doing 99% of the work.

However it doesn't state what what the differences are, or what philosophy this library follows when it comes to implementation differences or features.

In my case, I am looking to import the exact implementation of AOSP into my unit tests, so I can ensure tests that use `JSONObject` etc are running the same code as an Android device.
* Know Robolectric does this already, but I don't want the bloat and have the side effects it comes with. Simply looking for just the JSON library.

**Comment by tdunning** [comment]
This package was intended as an emergency stop-gap for Apache projects that had to urgently remove the org.json library. As such, compatibility with org.json over the APIs in use was critical, long-term viability and suitability for other purposes was not a goal. Documentation beyond what was required to meet that need was not a goal.

The differences from the Android version are small extensions or modifications that were required to bring the library up to the required level of compatibility and to add enough tests to believe that the code was correct. This worked. The projects in question were able to migrate away from the problematic libraries. Those projects subsequently migrated to supported JSON libraries that provided equivalent functionality with different APIs.

If you look at the (very short) commit history, you will see what the changes were since the first import was, I believe, was just the android version. Those changes include:

* [Lots of fiddly javadoc cleanups.](https://github.com/tdunning/open-json/commit/ba8698cda13a313c59b43b8a5881ad8b20b12d62)
* [Added constructor for JSONTokener that takes a Reader.](https://github.com/tdunning/open-json/commit/01855297ab37a4b0eec451d05528fd2157147627)
* [Convert JSONException to unchecked to match current json.org API.](https://github.com/tdunning/open-json/commit/68bd32beb1ac9219a40b9609f9d099ab0d7b6f22)
* [Escape / (really!) in the context </ to help HTML embedding](https://github.com/tdunning/open-json/commit/e1541126bf3206fa7a2b243f3791e274822128c1)
* [Closes](https://github.com/tdunning/open-json/commit/2530de15ee87bd7e4aaa17668777d7938f9e6fca) https://github.com/tdunning/open-json/issues/2 
* [- Don't escape quotes and such in output from special functions.](https://github.com/tdunning/open-json/commit/2530de15ee87bd7e4aaa17668777d7938f9e6fca)
* [put(Collection<?>) method is added to conform old json library](https://github.com/tdunning/open-json/commit/73a2d289c9938a53208daddc729f96f71c5fd719)
* [The surroundingQuotes field became redundant via other changes. Removed it.](https://github.com/tdunning/open-json/commit/cde2338d6e35b82f141b38ae1e0b56fc5650fb69)
* [Added constructor from bean Object.](https://github.com/tdunning/open-json/commit/3e693edafaa96f7267542434bfdffbff9d5f40b1)
* [Java 6 compatibility for JSONObject](https://github.com/tdunning/open-json/commit/2a29a6bd83c1e0fba6728cf20808260ad6b7f7e8)
* [Add static getNames method](https://github.com/tdunning/open-json/commit/c9162add9be27380bcae53d1135e2a5939f37a51)
* [Closes](https://github.com/tdunning/open-json/commit/9ae533316d72df8947ac6228aebad6885b8574d0) https://github.com/tdunning/open-json/issues/8
* [: Make JSONObject(Object) recurse properly, also make enums look like strings after conversion.](https://github.com/tdunning/open-json/commit/9ae533316d72df8947ac6228aebad6885b8574d0)
* [Some code is broken without JSONString interface](https://github.com/tdunning/open-json/commit/b2df4e045c864f0d9dd606989298e91c48be9fad)
* [Each JSONObject constructor should only throw runtime exceptions](https://github.com/tdunning/open-json/commit/6804489698bc3d13db80932733632c9d8f38dec4)

I really can't tell you anything more than what I (and others) wrote down 8 years ago. 

Note also that there are 14 forks of this library and the openjson library might suit your needs.

If you would like to take this project over, I wouldn't mind. But I do think that there are better courses of action.

**Comment by jkasten2** [comment]
@tdunning appreciate the quick response and details here!

>If you would like to take this project over, I wouldn't mind. But I do think that there are better courses of action.

I don't think I want to take this library over, since isn't exactly what I am looking for anyway.

I do want to say I have found this library useful so far for Android unit tests. I actually wanted an older snapshot of AOSP org.json for Android 5 compatibility testing. I'll take a look at those forks and evaluate other options for unit testing with newer Android versions and for the longer term though.

**Comment by tdunning** [comment]
That's cool.

And feel free to lift anything that helps you. If you want to grab all of the unit tests here and use them or some variation on them, feel free. There is no need to use this package as it is currently constructed. Do what you like and what helps you.

Heck, you could just take all the semi-colons and leave the code!
