### ISSUE TITLE
Don't escape character for JSONFunction

### ISSUE THREAD

**Issue by bitstorm** [tdunning/open-json#2]
Hi,

JSONStringer doesn't wrap JSONFunction object in order to preserve JavaScript code. This is ok but if we have quotes in our JavaScript (Example: { "value": window.myfunction(var str ="str") }) we get broken code as quotes are escaped (i.e. { "value": window.myfunction(var str =\"str\") }).
We should avoid character escaping for this entity. We could change the following line

 https://github.com/tdunning/open-json/blob/master/src/main/java/org/json/JSONStringer.java#L262

to out.append(value)

**Comment by tdunning** [comment]
Have you tested this change?

**Comment by tdunning** [comment]
I just pushed a fix and a test.  Can you verify?

**Comment by bitstorm** [comment]
Hi,

sorry but I don't see this commit. can you link it ?

Thank you.

**Comment by bitstorm** [comment]
I did a PR, so we can better discuss the issue

https://github.com/tdunning/open-json/pull/3

**Comment by klopfdreh** [comment]
Great. This looks better to me. @bitstorm  Maybe we can revert the change with the boolean to the string function, because we append the string as raw input in case of JSONFunction.

I would suggest the following reverts: 
https://github.com/tdunning/open-json/blob/2530de15ee87bd7e4aaa17668777d7938f9e6fca/src/main/java/org/json/JSONStringer.java#L323 - remove the boolean arg
https://github.com/tdunning/open-json/blob/2530de15ee87bd7e4aaa17668777d7938f9e6fca/src/main/java/org/json/JSONStringer.java#L324 - remove the if condition
https://github.com/tdunning/open-json/blob/2530de15ee87bd7e4aaa17668777d7938f9e6fca/src/main/java/org/json/JSONStringer.java#L383 - remove the if condition

As @bitstorm mentioned correctly other values should not been escaped, too because it causes javascript issues.

**Comment by bitstorm** [comment]
@klopfdreh 
Looks good to me as well: With this commit I was able to fix the problem with ModalWindow and with WicketStuff module select2. 
I'm +1 to to remove the flag for surroundingQuotes as it's not used any more (it's always set to true). But we should ask @tdunning  if it might be helpful in future.

**Comment by tdunning** [comment]
I don't see any future use. Let me look at the current state of the code
and get back.

**Comment by tdunning** [comment]
Nuked it. Intellij allows inlining of parameters and then semi-automated
optimization of the if statements. Very nice.

This will appear in next release which should be soon.

**Comment by klopfdreh** [comment]
Only for information / reference: https://github.com/apache/wicket/pull/193

**Comment by bitstorm** [comment]
@tdunning @klopfdreh  
thank you!
